---
- name: make repo from downloaded debs and dependecies
  hosts:  all
  vars:
    repo_name:  diag_soft   #name of apt local repo
    local_path: /mnt/distr/
    debs_folder:  /home/{{ansible_user}}/{{repo_name}}  #remote_host_folder
    apt_packages:
#      - curl
      - ffmpeg
  gather_facts: False
  tasks:

    - name: clear apt cache(/var/cache/apt/archives)
      shell:  apt-get clean
      become: true
    
    - name: apt download packs
      shell:  sudo apt-get install --download-only {{item}} -y
      become: true
      with_items:
        - "{{apt_packages}}"

    - name: rm /home/user/debs
      file:
        path: '{{debs_folder}}'
        state:  absent
      become: true

    - name: mkdir /home/user/debs
      file:
        path: '{{debs_folder}}'
        state:  directory
        owner:  '{{ansible_user}}'
        group:  '{{ansible_user}}'
        mode: '0755'

    - name: cp .deb to debs
      shell:  cp /var/cache/apt/archives/*.deb {{debs_folder}}/
      become: true

    - name: dpkg-scanpackages
      shell:  cd {{debs_folder}} && sudo dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
      become: true

#
    - name: rights
      shell:  chown -R {{ansible_user}}:{{ansible_user}} {{debs_folder}}
      become: true

    - name: file
      file:
        path: '{{debs_folder}}/{{repo_name}}.list'
        state:  touch
      become: true

    - name: fill .list
      shell: echo "deb [trusted=yes] file:/var/local/{{repo_name}}/ ./" | sudo tee {{debs_folder}}/{{repo_name}}.list
      become: true

    - name: arch
      archive:
        path: '{{debs_folder}}'
        dest: /home/{{ansible_user}}/{{repo_name}}.tgz
        format: gz

    - name: extract arch
      fetch:
        src:  /home/{{ansible_user}}/{{repo_name}}.tgz
        dest: '{{local_path}}'
        flat: yes


    - name: clear apt cache(/var/cache/apt/archives)
      shell:  apt-get clean
      become: true
      
